### ISSUE TITLE
Gull tracking data download problem

### ISSUE THREAD

**Issue by ablythed** [holoviz-topics/examples#176]
In Gull tracking (see latest version in #167), anaconda-project run gives the following error: 

      ERROR:tornado.application:Uncaught exception
      Traceback (most recent call last):
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/http1connection.py", line 689, in _read_chunked_body
          await ret
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/http1connection.py", line 736, in data_received
          ret = self._delegate.data_received(decompressed)
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/simple_httpclient.py", line 692, in data_received
          self.request.streaming_callback(chunk)
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/anaconda_project/internal/http_client.py", line 88, in writer
          self._progress.update(len(chunk) / 1024 / 1024)
      AttributeError: 'NoneType' object has no attribute 'update'
      ERROR:tornado.application:Exception in callback functools.partial(<function _HTTPConnection.__init__.<locals>.<lambda> at 0x7f9139e47820>, <Task finished name='Task-1' coro=<_HTTPConnection.run() done, defined at /Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/simple_httpclient.py:293> exception=_QuietException()>)
      Traceback (most recent call last):
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/http1connection.py", line 689, in _read_chunked_body
          await ret
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/http1connection.py", line 736, in data_received
          ret = self._delegate.data_received(decompressed)
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/simple_httpclient.py", line 692, in data_received
          self.request.streaming_callback(chunk)
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/anaconda_project/internal/http_client.py", line 88, in writer
          self._progress.update(len(chunk) / 1024 / 1024)
      AttributeError: 'NoneType' object has no attribute 'update'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
          ret = callback()
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/simple_httpclient.py", line 290, in <lambda>
          gen.convert_yielded(self.run()), lambda f: f.result()
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/simple_httpclient.py", line 444, in run
          await self._write_body(True)
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/simple_httpclient.py", line 524, in _write_body
          await self.connection.read_response(self)
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/http1connection.py", line 257, in _read_message
          await body_future
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/http1connection.py", line 689, in _read_chunked_body
          await ret
        File "/Users/adavis/opt/miniconda3/lib/python3.8/site-packages/tornado/http1connection.py", line 68, in __exit__
          raise _QuietException
      tornado.http1connection._QuietException
      Failed download to /Users/adavis/development/examples/gull_tracking/data/HG_OOSTENDE-gps-2018.csv: Connection closed
      missing requirement to run this project: A downloaded file which is referenced by DATAFILE.
        Environment variable DATAFILE is not set.
      (Use Ctrl+C to quit.)
      Value for DATAFILE:

**Comment by maximlt** [comment]
@jlstevens note that this issue appears with versions of anaconda-project that display a progress bar when downloading data. With `0.8.3` it works fine, this is the version pinned in the README. When I installed anaconda-project in the first place I didn't follow that pin since it seemed a little outdated. So to deploy this notebook and until there's a new version of anaconda-project that fixes this bug, you may have to use one of the older versions without the progress bar.

**Comment by jlstevens** [comment]
Thanks for tracking that down.

The progress bar was added to anaconda-project at our request so I'll file a bug report there. It probably just needs to catch the case when it can't show the progress bar (for whatever reason) and continue as normal.

**Comment by maximlt** [comment]
I've already opened an issue and submitted a PR there, it's linked above.

**Comment by jlstevens** [comment]
Ah, I missed that. Thanks!

**Comment by Azaya89** [comment]
Can this issue be closed, or is the problem still persisting?

**Comment by maximlt** [comment]
I think the problem has been solved in anaconda-project. @Azaya89 can you search in the repository if we recommend somewhere installing an older version of anaconda-project. If so, please update the docs to pin the latest version.

**Comment by Azaya89** [comment]
> I think the problem has been solved in anaconda-project. @Azaya89 can you search in the repository if we recommend somewhere installing an older version of anaconda-project. If so, please update the docs to pin the latest version.

Pls, what docs should I update? Is it the Contributing guide?

**Comment by maximlt** [comment]
It seems that there's one place where we recommend installing version 0.8.3. That should be updated.

https://github.com/search?q=repo%3Aholoviz-topics%2Fexamples%20%22anaconda-project%3D%22&type=code
